package io.smartpos.sales.api.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

import java.util.List;
import java.util.UUID;

/**
 * Payload for POST /api/v1/offline/sync — uploaded by a POS terminal that
 * accumulated sales while offline.
 *
 *   batch:    one upload (so the whole thing can be re-tried)
 *   items[].clientOpId: per-row idempotency key generated by the client
 *
 * The response mirrors items[] with the resolved server sale id (or error).
 */
public final class OfflineSyncDto {

    private OfflineSyncDto() {}

    public record BatchUpload(
            @NotNull UUID terminalId,
            @NotBlank String clientBatchId,
            @NotEmpty @Valid List<Item> items
    ) {}

    public record Item(
            @NotBlank String clientOpId,
            @NotNull @Valid CreateSaleRequest sale
    ) {}

    public record BatchResult(UUID batchId, int total, int success, int failed,
                              List<ItemResult> items) {}

    public record ItemResult(String clientOpId, UUID saleId, String status, String error) {}
}
