ALTER TABLE documents ADD COLUMN IF NOT EXISTS fiscal_code VARCHAR(50);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS z_number VARCHAR(50);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS receipt_number VARCHAR(50);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS buyer_tin VARCHAR(30);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS vfd_status VARCHAR(20) DEFAULT 'pending';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS vfd_submitted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS vfd_response JSONB;
