/**
 * Maps icon key strings (from the API menu response) to Tabler icon components.
 *
 * The API returns kebab-case icon names like "layout-dashboard", "cash-register".
 * This module converts them to Tabler PascalCase and resolves to React components.
 */
import type { ElementType } from 'react';
import {
  IconCircle,
  IconDashboard,
  IconLayoutDashboard,
  IconSearch,
  IconCashBanknote,
  IconCash,
  IconCashRegister,
  IconReceipt,
  IconFileInvoice,
  IconArrowBackUp,
  IconShoppingCart,
  IconPackage,
  IconUsers,
  IconTruck,
  IconTruckDelivery,
  IconBuildingWarehouse,
  IconBox,
  IconCoin,
  IconWallet,
  IconArrowsTransferDown,
  IconReceipt2,
  IconChartBar,
  IconDownload,
  IconSettings,
  IconUserShield,
  IconBuilding,
  IconWorld,
  IconBarcode,
  IconRepeat,
  IconChartInfographic,
  IconSparkles,
  IconBell,
  IconBook,
  IconBookmarks,
  IconCalculator,
  IconClipboardCheck,
  IconUsersGroup,
  IconClock,
  IconBeach,
  IconDeviceDesktop,
  IconFileImport,
  IconPlug,
  IconPrinter,
  IconLanguage,
  IconTag,
  IconBuildingStore,
  IconRuler,
  IconUpload,
  IconPercentage,
  IconGift,
  IconBellRinging,
  IconAdjustmentsAlt,
  IconCreditCard,
  IconSend,
  IconAlertTriangle,
  IconHistory,
  IconHelp,
  IconHelpCircle,
  IconKey,
  IconBrain,
  IconDeviceMobile,
  IconBug,
  IconDatabase,
  IconReceiptTax,
  IconMail,
  IconMessage,
  IconBrandWhatsapp,
  IconWebhook,
  IconCategory,
  IconPalette,
  IconAd,
  IconTools,
  IconAddressBook,
  IconSpeakerphone,
} from '@tabler/icons-react';

const iconRegistry: Record<string, ElementType> = {
  IconDashboard,
  IconLayoutDashboard,
  IconSearch,
  IconCashBanknote,
  IconCash,
  IconCashRegister,
  IconReceipt,
  IconFileInvoice,
  IconArrowBackUp,
  IconShoppingCart,
  IconPackage,
  IconUsers,
  IconTruck,
  IconTruckDelivery,
  IconBuildingWarehouse,
  IconBox,
  IconBoxes: IconBox,
  IconCoin,
  IconWallet,
  IconArrowsTransferDown,
  IconReceipt2,
  IconChartBar,
  IconDownload,
  IconSettings,
  IconUserShield,
  IconBuilding,
  IconWorld,
  IconBarcode,
  IconRepeat,
  IconChartInfographic,
  IconSparkles,
  IconBell,
  IconBook,
  IconBookmarks,
  IconCalculator,
  IconClipboardCheck,
  IconUsersGroup,
  IconClock,
  IconBeach,
  IconDeviceDesktop,
  IconFileImport,
  IconPlug,
  IconPrinter,
  IconLanguage,
  IconTag,
  IconBuildingStore,
  IconRuler,
  IconUpload,
  IconPercentage,
  IconGift,
  IconBellRinging,
  IconAdjustmentsAlt,
  IconCreditCard,
  IconSend,
  IconAlertTriangle,
  IconHistory,
  IconHelp,
  IconHelpCircle,
  IconKey,
  IconBrain,
  IconDeviceMobile,
  IconBug,
  IconDatabase,
  IconReceiptTax,
  IconMail,
  IconMessage,
  IconBrandWhatsapp,
  IconWebhook,
  IconCategory,
  IconPalette,
  IconAd,
  IconTools,
  IconAddressBook,
  IconMegaphone: IconSpeakerphone,
};

/**
 * Convert a kebab-case icon name from the database to a Tabler PascalCase name.
 * "layout-dashboard" → "IconLayoutDashboard"
 * "cash-register" → "IconCashRegister"
 */
function toTablerName(key: string): string {
  return 'Icon' + key
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** Resolve an icon key string to a React component. Returns IconCircle as fallback. */
export function mapIcon(key: string | null | undefined): ElementType {
  if (!key) return IconCircle;
  // Try direct lookup first (handles "IconDashboard" format)
  if (iconRegistry[key]) return iconRegistry[key];
  // Convert kebab-case to Tabler format and try again
  const tablerName = toTablerName(key);
  return iconRegistry[tablerName] ?? IconCircle;
}
